version: 2

project_name: toney
release:
  github:
    owner: SourcewareLab 
    name: toney

builds:
  - id: toney
    main: . 
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: toney

archives:
  - id: archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ['zip']

homebrew_casks:
  - name: toney 
    binary: toney
    description: "Toney - a fast, lightweight terminal-based note-taking app"
    homepage: "https://sourcewarelab.github.io/Toney/"
    url:
      template: "https://github.com/SourcewareLab/Toney/releases/download/v{{ .Version }}/toney_darwin_amd64.tar.gz"
    uninstall:
      delete:
        - "/usr/local/bin/toney"
    repository:
      owner: SourcewareLab
      name: homebrew-toney
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: NucleoFusion 
      email: lakshit.singh.mail@gmail.com 

nfpms:
  - id: deb
    formats:
      - deb
    section: utils
    priority: optional
    maintainer: "NucleoFusion <lakshit.singh.mail@gmail.com>"
    description: "Toney - a fast, lightweight terminal-based note-taking app"
    license: MIT
    vendor: NucleoFusion
    homepage: https://sourcewarelab.github.io/Toney/

  - id: rpm
    formats:
      - rpm
    section: utils
    priority: optional
    maintainer: "NucleoFusion <lakshit.singh.mail@gmail.com>"
    description: "Toney - a fast, lightweight terminal-based note-taking app"
    license: MIT
    vendor: NucleoFusion
    homepage: https://sourcewarelab.github.io/Toney/

checksum:
  name_template: 'checksums.txt'


